### ISSUE TITLE
error while building on macOS

### ISSUE THREAD

**Issue by Ivoah** [daniel-e/tetros#1]
```
Samantha:tetros ivo$ make
nasm -d DEBUG -f bin tetros.asm -o tetros.img
tetros.asm:93: error: expression syntax error
tetros.asm:157: error: expression syntax error
tetros.asm:256: error: expression syntax error
tetros.asm:281: error: expression syntax error
make: *** [tetros.img] Error 1
Samantha:tetros ivo$
```

**Comment by hedavies98** [comment]
Try using [this](https://gist.github.com/DraftYeti5608/d2f8446fc5240297168a5e90e481eec0), .asm file. I think this error is because `loop` and `dd` are already instructions in NASM.

**Comment by Ivoah** [comment]
still doesn't work correctly

```
Samantha:tetros ivo$ nasm -f bin tetros.asm.1 tetros.img
nasm: error: more than one input file specified
type `nasm -h' for help
Samantha:tetros ivo$ nasm -f bin tetros.asm.1 -o tetros.img
tetros.asm.1:312: error: TIMES value -6 is negative
Samantha:tetros ivo$
```

**Comment by hedavies98** [comment]
Unfortunatley i don't know how to fix that issue

**Comment by richgieg** [comment]
It looks like the generated code ends up being 452 bytes, rather than the maximum 446 (specified at line 312), causing the "TIMES value -6 is negative" error.

@Ivoah What version of NASM are you using?

**Comment by ghost** [comment]
For what it's worth, the image builds just fine for me on OSX El Capitan. I installed nasm via brew. The the stat command in the makefile, however, doesn't work due to BSD vs. Linux syntax.

**Comment by Ivoah** [comment]
Installing NASM through homebrew fixed the assembly error, but I was still getting errors with stat. I then installed binutils through homebrew and changed the call to `stat` in the makefile to `gstat`, and it works!

**Comment by daniel-e** [comment]
Many thanks for solving the problem. I have merged your pull request to the master.
