### ISSUE TITLE
Cannot boot bare metal

### ISSUE THREAD

**Issue by boredcoder411** [daniel-e/tetros#4]
tetros.img boots fine in qemu, and the command to write to a usb stick also worked, but my computer wont see it as bootable. hexdump shows that the signature 0xaa55 is there.

**Comment by boredcoder411** [comment]
I went into my UEFI firmware, and enabled CMS. This is bc this project uses MBR and not UEFI.

**Comment by daniel-e** [comment]
Many thanks for adding the solution. That might be very helpful for people with the same problem.
